name: flutter_phone_state_example
description: Demonstrates how to use the flutter_phone_state plugin.
publish_to: 'none'

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_phone_state:
    path: ../
flutter:
  uses-material-design: true